# Generated by Django 4.0.1 on 2022-01-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Username',
            new_name='username',
        ),
    ]
