# Generated by Django 4.0.1 on 2022-01-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标题'),
        ),
    ]
